
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

[prune]
  unused-packages = true
  go-tests = true

[[constraint]]
  name = "github.com/sirupsen/logrus"
  source = "github.com/gravitational/logrus"
  version = "1.0.6"

[[constraint]]
  name = "github.com/gravitational/trace"
  branch = "master"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.13.0"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.13.0"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.13.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "=v10.0.0"

[[override]]
  name = "gopkg.in/yaml.v2"
  version = "=v2.2.2"

[[override]]
name = "cloud.google.com/go"
revision = "3b1ae45394a234c385be014e9a488f2bb6eef821"

[[override]]
name = "github.com/Azure/go-autorest"
revision = "58f6f26e200fa5dfb40c9cd1c83f3e2c860d779d"

[[override]]
name = "github.com/PuerkitoBio/purell"
revision = "8a290539e2e8629dbc4e6bad948158f790ec31f4"

[[override]]
name = "github.com/PuerkitoBio/urlesc"
revision = "5bd2802263f21d8788851d5305584c82a5c75d7e"

[[override]]
name = "github.com/coreos/go-oidc"
revision = "a4973d9a4225417aecf5d450a9522f00c1f7130f"

[[override]]
name = "github.com/coreos/pkg"
revision = "fa29b1d70f0beaddd4c7021607cc3c3be8ce94b8"

[[override]]
name = "github.com/dgrijalva/jwt-go"
revision = "01aeca54ebda6e0fbfafd0a524d234159c05ec20"

[[override]]
name = "github.com/docker/spdystream"
revision = "449fdfce4d962303d702fec724ef0ad181c92528"

[[override]]
name = "github.com/emicklei/go-restful"
revision = "ff4f55a206334ef123e4f79bbf348980da81ca46"

[[override]]
name = "github.com/emicklei/go-restful-swagger12"
revision = "dcef7f55730566d41eae5db10e7d6981829720f6"

[[override]]
name = "github.com/ghodss/yaml"
revision = "73d445a93680fa1a78ae23a5839bad48f32ba1ee"

[[override]]
name = "github.com/go-openapi/jsonpointer"
revision = "46af16f9f7b149af66e5d1bd010e3574dc06de98"

[[override]]
name = "github.com/go-openapi/jsonreference"
revision = "13c6e3589ad90f49bd3e3bbe2c2cb3d7a4142272"

[[override]]
name = "github.com/go-openapi/spec"
revision = "6aced65f8501fe1217321abf0749d354824ba2ff"

[[override]]
name = "github.com/go-openapi/swag"
revision = "1d0bd113de87027671077d3c71eb3ac5d7dbba72"

[[override]]
name = "github.com/gogo/protobuf"
revision = "c0656edd0d9eab7c66d1eb0c568f9039345796f7"

[[override]]
name = "github.com/golang/glog"
revision = "44145f04b68cf362d9c4df2182967c2275eaefed"

[[override]]
name = "github.com/golang/groupcache"
revision = "02826c3e79038b59d737d3b1c0a1d937f71a4433"

[[override]]
name = "github.com/golang/protobuf"
revision = "4bd1920723d7b7c925de087aa32e2187708897f7"

[[override]]
name = "github.com/google/btree"
revision = "7d79101e329e5a3adf994758c578dab82b90c017"

[[override]]
name = "github.com/google/gofuzz"
revision = "44d81051d367757e1c7c6a5a86423ece9afcf63c"

[[override]]
name = "github.com/gophercloud/gophercloud"
revision = "2bf16b94fdd9b01557c4d076e567fe5cbbe5a961"

[[override]]
name = "github.com/gregjones/httpcache"
revision = "787624de3eb7bd915c329cba748687a3b22666a6"

[[override]]
name = "github.com/hashicorp/golang-lru"
revision = "a0d98a5f288019575c6d1f4bb1573fef2d1fcdc4"

[[override]]
name = "github.com/howeyc/gopass"
revision = "bf9dde6d0d2c004a008c27aaee91170c786f6db8"

[[override]]
  name = "github.com/imdario/mergo"
  version = "=v0.3.6"

[[override]]
name = "github.com/jonboulle/clockwork"
revision = "72f9bd7c4e0c2a40055ab3d0f09654f730cce982"

[[override]]
name = "github.com/json-iterator/go"
version = "=1.1.5"

[[override]]
name = "github.com/juju/ratelimit"
revision = "5b9ff866471762aa2ab2dced63c9fb6f53921342"

[[override]]
name = "github.com/mailru/easyjson"
revision = "d5b7844b561a7bc640052f1b935f7b800330d7e0"

[[override]]
name = "github.com/peterbourgon/diskv"
revision = "5f041e8faa004a95c88a202771f4cc3e991971e6"

[[override]]
name = "github.com/pmezard/go-difflib"
revision = "d8ed2627bdf02c080bf22230dbb337003b7aba2d"

[[override]]
name = "github.com/spf13/pflag"
revision = "9ff6c6923cfffbcd502984b8e0c80539a94968b7"

[[override]]
name = "github.com/stretchr/testify"
revision = "f6abca593680b2315d2075e0f5e2a9751e3f431a"

[[override]]
name = "golang.org/x/crypto"
revision = "81e90905daefcd6fd217b62423c0908922eadb30"

[[override]]
name = "golang.org/x/net"
revision = "1c05540f6879653db88113bc4a2b70aec4bd491f"

[[override]]
name = "golang.org/x/oauth2"
revision = "a6bd8cefa1811bd24b86f8902872e4e8225f74c4"

[[override]]
name = "golang.org/x/sys"
revision = "7ddbeae9ae08c6a06a59597f0c9edbc5ff2444ce"

[[override]]
name = "golang.org/x/text"
revision = "b19bf474d317b857955b12035d2c5acb57ce8b01"

[[override]]
name = "gopkg.in/inf.v0"
revision = "3887ee99ecf07df5b447e9b00d9c0b2adaa9f3e4"

[[override]]
name = "k8s.io/kube-openapi"
revision = "868f2f29720b192240e18284659231b440f9cda5"
